version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - ./scraper/:/app/scraper
      - ./scripts/:/app/scripts
      - ./logs/:/app/logs
    ports:
      - $LOCAL_APP_PORT:8888
    env_file:
      - ./.env
    tty: true
    entrypoint: jupyter notebook --ip 0.0.0.0 --port 8888 --no-browser --allow-root